/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.40
 * Generated at: 2021-03-02 09:31:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class memberJoin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"utf-8\" />\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" />\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 타이틀 바 -->\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"img/logo_img.PNG\" >\r\n");
      out.write("\t<title>축축빵빵 - 회원가입</title>\r\n");
      out.write("\r\n");
      out.write("\t<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- CSS Files -->\r\n");
      out.write("    <link href=\"../css/bootstrap.min_join.css\" rel=\"stylesheet\" />\r\n");
      out.write("\t<link href=\"../css/join.css\" rel=\"stylesheet\" />\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<!-- Fonts and Icons -->\r\n");
      out.write("    <link href=\"https://netdna.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href='https://fonts.googleapis.com/css?family=Muli:400,300' rel='stylesheet' type='text/css'>\r\n");
      out.write("\t<link href=\"../css/join_themify-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!--   Core JS Files   -->\r\n");
      out.write("\t<script src=\"../js/jquery-3.5.1.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"../js/bootstrap.min_join.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"../js/jquery.bootstrap.wizard_join.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!--  Plugin for the Wizard -->\r\n");
      out.write("\t<script src=\"../js/demo_join.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"../js/paper-bootstrap-wizard_join.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!--  More information about jquery.validate here: https://jqueryvalidation.org/\t -->\r\n");
      out.write("\t<script src=\"../js/jquery.validate.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write(" \t<!-- 주소 찾기 기능-->\r\n");
      out.write("    <script src=\"../js/findAddress.js\"></script>\r\n");
      out.write("    <script src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t</head>\r\n");
      out.write("\t\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t\r\n");
      out.write("\t<div class=\"image-container set-full-height\" style=\"background-color: lightblue\">\r\n");
      out.write("\t    <!--   작은 로고 넣어서 메인 페이지로 돌아갈 수 있게끔   -->\r\n");
      out.write("\r\n");
      out.write("            <!-- <div class=\"logo-container\">\r\n");
      out.write("                <div class=\"logo\" >\r\n");
      out.write("                <a href=\"#\">\r\n");
      out.write("                <img src=\"img/logo.PNG\">\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            </a>\r\n");
      out.write("\t            <div class=\"brand\">축축빵빵</div>\r\n");
      out.write("\t            \r\n");
      out.write("\t        </div> -->\r\n");
      out.write("\r\n");
      out.write("\t    <!--   Big container   -->\r\n");
      out.write("\t    <div class=\"container\">\r\n");
      out.write("\t        <div class=\"row\">\r\n");
      out.write("\t\t        <div class=\"col-sm-8 col-sm-offset-2\">\r\n");
      out.write("\r\n");
      out.write("\t\t            <!--      Wizard container        -->\r\n");
      out.write("\t\t            <div class=\"wizard-container\">\r\n");
      out.write("\r\n");
      out.write("\t\t                <div class=\"card wizard-card\" data-color=\"blue\" id=\"wizardProfile\">\r\n");
      out.write("\t\t                    <form action=\"\" method=\"\">\r\n");
      out.write("\t\t                <!--        You can switch \" data-color=\"orange\" \"  with one of the next bright colors: \"blue\", \"green\", \"orange\", \"red\", \"azure\"          -->\r\n");
      out.write("\r\n");
      out.write("\t\t                    \t<div class=\"wizard-header text-center\">\r\n");
      out.write("\t\t                        \t<h3 class=\"wizard-title\">회원가입</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"category\">회원가입에 필요한 당신의 정보를 적어주세요.</p>\r\n");
      out.write("\t\t                    \t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"wizard-navigation\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"progress-with-circle\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t     <div class=\"progress-bar\" role=\"progressbar\" aria-valuenow=\"1\" aria-valuemin=\"1\" aria-valuemax=\"3\" style=\"width: 21%;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t                            <li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"#about\" data-toggle=\"tab\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"icon-circle\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ti-user\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t기본정보\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t                            <!-- <li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"#account\" data-toggle=\"tab\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"icon-circle\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ti-settings\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t추가정보\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li> -->\r\n");
      out.write("\t\t\t                            <li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"#address\" data-toggle=\"tab\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"icon-circle\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ti-map\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t가입완료\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t                        </ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t                        <div class=\"tab-content\">\r\n");
      out.write("\t\t                            <div class=\"tab-pane\" id=\"about\">\r\n");
      out.write("\t\t                            \t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-10 col-sm-offset-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label>이름</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input name=\"name\" id=\"name\" type=\"text\" class=\"form-control\" placeholder=\"홍길동\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label>아이디 </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input id =\"customer_id\" name=\"customer_id\" type=\"text\" class=\"form-control\" placeholder=\"Smith...\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div id='idCheckResult' style=\"width:200px;color:red\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label>비밀번호 </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input name=\"password\" id=\"password\"type=\"password\" class=\"form-control\" placeholder=\"문자, 숫자, 특수문자조합으로 8자리 이상\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label>비밀번호 확인</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input id=\"passwordconfirm\" name=\"passwordconfirm\" type=\"password\" class=\"form-control\" placeholder=\"문자, 숫자, 특수문자조합으로 8자리 이상\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label>생년월일 </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input name='birthday' id='birthday' type=\"date\" class=\"form-control\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-10 col-sm-offset-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label>전화번호</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input name=\"tel\" type=\"tel\" id='tel' class=\"form-control\" placeholder=\"휴대폰번호를 입력하고 인증번호를 받아주세요.\">\r\n");
      out.write("                                                    <button id=\"getVerifyNumberButton\" class=\"form-control\">인증번호 받기</button>\r\n");
      out.write("                                                    <input type=\"text\" name=\"sms\" id=\"sms\" class=\"form-control\" placeholder=\"인증번호를 입력해주세요.\" disabled>\r\n");
      out.write("                                                    <button id=\"verifyButton\" class=\"form-control\">인증</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label>Email </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input id='email' name=\"email\" type=\"email\" class=\"form-control\" placeholder=\"andrew@creative-tim.com\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label>주소 </label>\r\n");
      out.write("                \t\t\t\t\t\t\t\t\t<input type=\"button\" value=\"주소찾기\" id=\"findAddr\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"우편번호\" id=\"zonecode\" class=\"form-control\">\r\n");
      out.write("               \t\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("                  \t\t\t\t\t\t\t\t\t\t&emsp;&emsp;&emsp;&emsp;<input type=\"text\" size=\"35\" placeholder=\"도로명주소 또는 지번주소\" id=\"addr\" class=\"form-control\">\r\n");
      out.write("                \t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("               \t\t\t\t\t\t\t\t\t\t\t&emsp;&emsp;&emsp;&emsp;<input type=\"text\" placeholder=\"상세 주소란\" id=\"detailAddr\" class=\"form-control\">    \r\n");
      out.write("                \t\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"동\" id=\"extraAddr\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t                            </div>\r\n");
      out.write("\r\n");
      out.write("\t\t                            <div class=\"tab-pane\" id=\"address\">\r\n");
      out.write("\t\t                                <div class=\"row\">\r\n");
      out.write("\t\t                                    <div class=\"col-sm-12\">\r\n");
      out.write("\t\t                                        <h5 class=\"info-text\"></h5>\r\n");
      out.write("\t\t                                        <h5 class=\"info-text\">축축빵빵의 가족이 되신 것을 환영합니다!</h5>\r\n");
      out.write("\t\t                                    </div>\r\n");
      out.write("\t\t                                    \r\n");
      out.write("\t\t                                </div>\r\n");
      out.write("\t\t                            </div>\r\n");
      out.write("\t\t                        </div>\r\n");
      out.write("\t\t                        <div class=\"wizard-footer\">\r\n");
      out.write("\t\t                            <div class=\"pull-right\">\r\n");
      out.write("\t\t                                <input type='button' class='btn btn-next btn-fill btn-warning btn-wd' name='next' value='다음' />\r\n");
      out.write("\t\t                                <input type='button' class='btn btn-finish btn-fill btn-warning btn-wd' name='finish' value='회원가입' id='joinbtn'/>\r\n");
      out.write("\t\t                            </div>\r\n");
      out.write("\r\n");
      out.write("\t\t                            <div class=\"pull-left\">\r\n");
      out.write("\t\t                                <input type='button' class='btn btn-previous btn-default btn-wd' name='previous' value='이전' />\r\n");
      out.write("\t\t                            </div>\r\n");
      out.write("\t\t                            <div class=\"clearfix\"></div>\r\n");
      out.write("\t\t                        </div>\r\n");
      out.write("\t\t                    </form>\r\n");
      out.write("\t\t                </div>\r\n");
      out.write("\t\t            </div> <!-- wizard container -->\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t    \t</div><!-- end row -->\r\n");
      out.write("\t\t</div> <!--  big container -->\r\n");
      out.write("\r\n");
      out.write("\t   \r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\t\r\n");
      out.write("\t// 휴대전화 인증 상태\r\n");
      out.write("\tlet verified = false;\r\n");
      out.write("\t\r\n");
      out.write("\t$('#joinbtn').click(function () {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (verified) {\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype :'post',\r\n");
      out.write("\t\t\t\tasync :true,\r\n");
      out.write("\t\t\t\turl : \"memberRegister.do\",\r\n");
      out.write("\t\t\t\tcontentType:'application/x-www-form-urlencoded;charset=euc-kr', // 한글처리\r\n");
      out.write("\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t'id':$('#customer_id').val(),\r\n");
      out.write("\t\t\t\t\t'password':$('#password').val(),\r\n");
      out.write("\t\t\t\t\t'name':$('#name').val(),\r\n");
      out.write("\t\t\t\t\t'tel':$('#tel').val(),\r\n");
      out.write("\t\t\t\t\t'email':$('#email').val(),\r\n");
      out.write("\t\t\t\t\t'address':$('#zonecode').val() +\"/\"+$('#addr').val()+\"/\"+$('#detailAddr').val()+\"/\"+$('#extraAddr').val(),\r\n");
      out.write("\t\t\t\t\t'birthday':$('#birthday').val()\r\n");
      out.write("\t\t\t\t\t// 'gender' : $('input[name=\"gender\"]:checked').val(),\r\n");
      out.write("\t\t\t\t\t// 'skintype' :$('input[name=\"skin\"]:checked').val()\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tsuccess: function(result){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif (result == 1) {\r\n");
      out.write("\t\t\t\t\t\tlocation.replace(\"http://localhost:8080/index.jsp\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(err){console.log(err)}\r\n");
      out.write("\t\t\t});\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse {\r\n");
      out.write("\t\t\talert(\"전화번호 인증을 먼저 받으십시오.\")\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t  \r\n");
      out.write("\t})\r\n");
      out.write("\r\n");
      out.write("\t$('#customer_id').focusout(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($('#customer_id').val().length < 3){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#idCheckResult').text('사용불가합니다.');\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype: 'post', //전송방식\r\n");
      out.write("\t\t    \tasync : true, //비동기통신\r\n");
      out.write("\t\t    \turl : 'idCheck.do', // ***요청(request)\r\n");
      out.write("\t\t    \tcontentType : 'application/x-www-form-urlencoded;charset=euc-kr', // 한글처리\r\n");
      out.write("\t\t    \tdata :{'id': $('#customer_id').val()}, //보내는 데이타\r\n");
      out.write("\t\t    \tsuccess : function(result){\r\n");
      out.write("\t\t    \t\t$('#idCheckResult').text(result);\r\n");
      out.write("\t\t    \t},\r\n");
      out.write("\t\t    \terror: function(err){console.log(err);}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t})\r\n");
      out.write("\r\n");
      out.write("\t$('#getVerifyNumberButton').on('click', function() {\r\n");
      out.write("\t\t$('#sms').attr('disabled', false);\r\n");
      out.write("\t\t$('#sms').focus();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl: \"sendSms.do\",\r\n");
      out.write("\t\t\t\tdata: { \r\n");
      out.write("\t\t\t\t\t\treceiver: $(\"#tel\").val() \r\n");
      out.write("\t\t\t\t\t\t}, \r\n");
      out.write("\t\t\t\ttype: \"post\",\r\n");
      out.write("\t\t\t\tsuccess: function(result) {\r\n");
      out.write("\t\t\t\t\tconsole.log(result);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}, \r\n");
      out.write("\t\t\t\terror: function (error) {\r\n");
      out.write("\t\t\t\t\tconsole.log(error)\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t}); \r\n");
      out.write("\t\t\r\n");
      out.write("\t})\r\n");
      out.write("\r\n");
      out.write("\t$('#verifyButton').on('click', function() {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl: \"smsCheck.do\",\r\n");
      out.write("\t\t\t\ttype: \"post\",\r\n");
      out.write("\t\t\t\tdata: { \r\n");
      out.write("\t\t\t\t\tcode: $(\"#sms\").val()\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tsuccess: function(result) {\r\n");
      out.write("\t\t\t\t\t\tif (result == \"ok\") {\r\n");
      out.write("\t\t\t\t\t\t\talert(\"전화번호 인증에 성공했습니다.\"); \r\n");
      out.write("\t\t\t\t\t\t\tverified = true;\r\n");
      out.write("\t\t\t\t\t\t\t$('#verifyButton').text('인증 완료');\t\r\n");
      out.write("\t\t\t\t\t\t\t$('#verifyButton').attr('disabled', true);\r\n");
      out.write("\t\t\t\t\t\t} \r\n");
      out.write("\t\t\t\t\t\telse { \r\n");
      out.write("\t\t\t\t\t\t\talert(\"번호 인증 실패\"); \r\n");
      out.write("\t\t\t\t\t\t} \r\n");
      out.write("\t\t\t\t\t} \r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t})\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
