/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.39
 * Generated at: 2021-03-04 12:03:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class festival_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <meta name=\"description\" content=\"ddffddff.\">\r\n");
      out.write("    <meta name=\"author\" content=\"Ansonika\">\r\n");
      out.write("    <title>축축빵빵 - 축제 Main</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicons-->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"img/logo_img.PNG\" type=\"image/x-icon\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" type=\"image/x-icon\" href=\"img/apple-touch-icon-57x57-precomposed.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" type=\"image/x-icon\" sizes=\"72x72\" href=\"img/apple-touch-icon-72x72-precomposed.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" type=\"image/x-icon\" sizes=\"114x114\" href=\"img/apple-touch-icon-114x114-precomposed.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" type=\"image/x-icon\" sizes=\"144x144\" href=\"img/apple-touch-icon-144x144-precomposed.png\">\r\n");
      out.write("\r\n");
      out.write("    <!-- GOOGLE WEB FONT -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Gochi+Hand&family=Montserrat:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- COMMON CSS -->\r\n");
      out.write("\t<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"css/vendors.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- CUSTOM CSS -->\r\n");
      out.write("\t<link href=\"css/custom.css\" rel=\"stylesheet\">\r\n");
      out.write("        \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"preloader\">\r\n");
      out.write("        <div class=\"sk-spinner sk-spinner-wave\">\r\n");
      out.write("            <div class=\"sk-rect1\"></div>\r\n");
      out.write("            <div class=\"sk-rect2\"></div>\r\n");
      out.write("            <div class=\"sk-rect3\"></div>\r\n");
      out.write("            <div class=\"sk-rect4\"></div>\r\n");
      out.write("            <div class=\"sk-rect5\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- End Preload -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"layer\"></div>\r\n");
      out.write("    <!-- Mobile menu overlay mask -->\r\n");
      out.write("\r\n");
      out.write("    <!-- ====================헤더========================= -->\r\n");
      out.write("    <header>\r\n");
      out.write("        <div id=\"top_line\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-6\"><i class=\"icon-phone\"></i><strong>02-1234-5678</strong></div>\r\n");
      out.write("                    <div class=\"col-6\">\r\n");
      out.write("                        <ul id=\"top_links\">\r\n");
      out.write("                            <li><a href=\"#sign-in-dialog\" id=\"access_link\">로그인</a></li>\r\n");
      out.write("                            <!-- 로그인 세션이 있으면, 모든 페이지의 헤더 부분이 56~59행 처럼 나와야 함. -->\r\n");
      out.write("                            <!-- <li><span style=\"color: blue;\">홍길동</span>님 환영합니다</li>\r\n");
      out.write("                            <li><a href=\"mypage.jsp\" id=\"mypage\" class=\"icon-key-4\">myPage</a></li>\r\n");
      out.write("                            <li><a href=\"course_list.jsp\" id=\"wishlist_link\">나의 코스 목록</a></li>\r\n");
      out.write("                            <li><a href=\"#\" class=\"icon-logout\">로그아웃</a></li> -->\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div><!-- End row -->\r\n");
      out.write("            </div><!-- End container-->\r\n");
      out.write("        </div><!-- End top line-->\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-3\">\r\n");
      out.write("                    <div id=\"logo_home\">\r\n");
      out.write("                    \t<h1><a href=\"main.jsp\" title=\"메인 페이지 앵커\">축축빵빵</a></h1>\r\n");
      out.write("                        <!-- 로그인 세션이 있으면, 로고 클릭 시 mainAfterLogin.jsp로 이동되게-->\r\n");
      out.write("                        <!-- <h1><a href=\"mainAfterLogin.jsp\" title=\"메인 페이지 앵커\">축축빵빵</a></h1> -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <nav class=\"col-9\">\r\n");
      out.write("                    <a class=\"cmn-toggle-switch cmn-toggle-switch__htx open_close\" href=\"javascript:void(0);\"><span>Menu mobile</span></a>\r\n");
      out.write("                    <div class=\"main-menu\">\r\n");
      out.write("                        <div id=\"header_menu\">\r\n");
      out.write("                            <img src=\"img/logo_sticky.png\" width=\"160\" height=\"34\" alt=\"City tours\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <a href=\"#\" class=\"open_close\" id=\"close_in\"><i class=\"icon_set_1_icon-77\"></i></a>\r\n");
      out.write("                         <ul>\r\n");
      out.write("                            <li class=\"submenu\">\r\n");
      out.write("                                <a href=\"main.jsp\" class=\"show-submenu\" style=\"font-size: large;\">홈<i class=\"icon-home\"></i>\r\n");
      out.write("                                <!-- 로그인 세션이 있으면, 홈 버튼 클릭 시 mainAfterLogin.jsp로 이동되게-->\r\n");
      out.write("                                <!-- <a href=\"mainAfterLogin.jsp\" class=\"show-submenu\" style=\"font-size: large;\">홈<i class=\"icon-home\"></i> -->\r\n");
      out.write("                                    \r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"submenu\">\r\n");
      out.write("                                <a href=\"#\" class=\"show-submenu\" style=\"font-size: large;\">축제 <i class=\"icon-down-open-mini\"></i></a>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"festival.jsp\">축제</a></li>\r\n");
      out.write("                                    <li><a href=\"accommodations_list.jsp\">숙박</a></li>\r\n");
      out.write("                                    <li><a href=\"restaurants_list.jsp\">식당</a></li>\r\n");
      out.write("                                    <!-- <li class=\"third-level\"><a href=\"javascript:void(0);\">테스트</a>\r\n");
      out.write("                                        <ul>\r\n");
      out.write("                                            <li><a href=\"#\">테스트2</a></li>\r\n");
      out.write("                                            <li><a href=\"#\">테스트3</a></li>\r\n");
      out.write("                                            <li><a href=\"#\">테스트4</a></li>\r\n");
      out.write("                                            <li><a href=\"#\">테스트5</a></li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </li> -->\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"submenu\">\r\n");
      out.write("                                <a href=\"#\" class=\"show-submenu\" style=\"font-size: large;\">메이트 <i class=\"icon-down-open-mini\"></i></a>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <!-- 메이트서비스 아닌 회원은 mate_index_default -->\r\n");
      out.write("                                    <!-- 메이트서비스 회원은 mate_index -->\r\n");
      out.write("                                    <li><a href=\"mate/mate_index_default.jsp\">메이트 서비스는?</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">나의 메이트 </a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                             <li class=\"submenu\">\r\n");
      out.write("                                <a href=\"#\" class=\"show-submenu\" style=\"font-size: large;\">코스 <i class=\"icon-down-open-mini\"></i></a><ul>\r\n");
      out.write("                                    <li><a href=\"course_main.jsp\">코스 자랑 마당</a></li>\r\n");
      out.write("                                    <!-- 나의 코스 목록은 로그인 세션 있을 때만 접근 가능. 없으면 로그인하게-->\r\n");
      out.write("                                    <li><a href=\"course_list.jsp\">나의 코스 목록</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div><!-- End main-menu -->\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- 헤더 메뉴 아이콘 -->\r\n");
      out.write("                    <ul id=\"top_tools\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"javascript:void(0);\" class=\"search-overlay-menu-btn\"><i class=\"icon_search\"></i></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <!-- 즐겨찾기.. 장바구니처럼 넣는 거 하느냐 마느냐~ 고민쓰-->\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <div class=\"dropdown dropdown-cart\">\r\n");
      out.write("                                <a href=\"#\" data-toggle=\"dropdown\" class=\"cart_bt\"><i class=\"icon_bag_alt\"></i><strong>3</strong></a>\r\n");
      out.write("                                <ul class=\"dropdown-menu\" id=\"cart_items\">\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <div class=\"image\"><img src=\"img/thumb_cart_1.jpg\" alt=\"image\"></div>\r\n");
      out.write("                                        <strong><a href=\"#\">Louvre museum</a>1x $36.00 </strong>\r\n");
      out.write("                                        <a href=\"#\" class=\"action\"><i class=\"icon-trash\"></i></a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <div class=\"image\"><img src=\"img/thumb_cart_2.jpg\" alt=\"image\"></div>\r\n");
      out.write("                                        <strong><a href=\"#\">Versailles tour</a>2x $36.00 </strong>\r\n");
      out.write("                                        <a href=\"#\" class=\"action\"><i class=\"icon-trash\"></i></a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <div class=\"image\"><img src=\"img/thumb_cart_3.jpg\" alt=\"image\"></div>\r\n");
      out.write("                                        <strong><a href=\"#\">Versailles tour</a>1x $36.00 </strong>\r\n");
      out.write("                                        <a href=\"#\" class=\"action\"><i class=\"icon-trash\"></i></a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <div>Total: <span>$120.00</span></div>\r\n");
      out.write("                                        <a href=\"cart.jsp\" class=\"button_drop\">Go to cart</a>\r\n");
      out.write("                                        <a href=\"payment.jsp\" class=\"button_drop outline\">Check out</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div><!-- End dropdown-cart-->\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div><!-- container -->\r\n");
      out.write("    </header><!-- ====================헤더 끝 ====================== -->\r\n");
      out.write("    \r\n");
      out.write("    <!-- 메인 이미지 슬라이더 -->\r\n");
      out.write("\t<section id=\"hero\">\r\n");
      out.write("\t<img src =\"/img/login/kakao_login2.png\">\r\n");
      out.write("\t\t<div class=\"intro_title\">\r\n");
      out.write("\t\t\t<h3 class=\"animated fadeInDown\">삼척 <strong id=\"js-rotating\">2021,달빛아래,소원하는,일상</strong> 정월대보름제</h3>\r\n");
      out.write("\t\t\t<p class=\"animated fadeInDown\">달빛아래 소원해요, 함께하는 일상</p>\r\n");
      out.write("\t\t   <a href=\"festival_detail.jsp\" class=\"animated fadeInUp button_intro\">더 보기</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section><!-- End 메인 이미지 슬라이더 -->\r\n");
      out.write("\r\n");
      out.write("\t<main>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container margin_60\">\r\n");
      out.write("         \r\n");
      out.write("        <!-- 월별 축제 이미지 -->\r\n");
      out.write("            <div class=\"main_title\">\r\n");
      out.write("                <h2><a href=\"#\">◀</a><span class=\"month\">2 월</span><a href=\"#\">▶</a></h2>\r\n");
      out.write("            </div>\r\n");
      out.write("            <p class=\"main_description\">겨울이 끝나기 전에 <span>계절이 지나면 경험하기 힘들죠</span></p>\r\n");
      out.write("            <div class=\"row small-gutters categories_grid\">\r\n");
      out.write("                <div class=\"col-sm-12 col-md-12 bigimage\">\r\n");
      out.write("                    <a href=\"festival_detail.jsp\".jsp\">\r\n");
      out.write("                        <img src=\"img/img_cat_home_1.jpg\" alt=\"\" class=\"img-fluid\">\r\n");
      out.write("                        <div class=\"wrapper\">\r\n");
      out.write("                            <h2>국립민속박물관 정월대보름 한마당</h2>\r\n");
      out.write("                            <p>(02.01~03.03)</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm-12 col-md-12\">\r\n");
      out.write("                    <div class=\"row small-gutters mt-md-0 mt-sm-2\">\r\n");
      out.write("                        <div class=\"col-sm-3\">\r\n");
      out.write("                            <a href=\"all_tours_list.jsp\">\r\n");
      out.write("                                <img src=\"img/img_cat_home_2.jpg\" alt=\"\" class=\"img-fluid\">\r\n");
      out.write("                                <div class=\"wrapper\">\r\n");
      out.write("                                    <h2>홍성 남당항 새조개 온라인축제</h2>\r\n");
      out.write("                                    <p>(3.3~4.1)</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-sm-3\">\r\n");
      out.write("                            <a href=\"all_hotels_list.jsp\">\r\n");
      out.write("                                <img src=\"img/img_cat_home_3.jpg\" alt=\"\" class=\"img-fluid\">\r\n");
      out.write("                                <div class=\"wrapper\">\r\n");
      out.write("                                    <h2>어딘지 모르겠다~</h2>\r\n");
      out.write("                                    <p>아무데서나 놀자~</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-sm-3\">\r\n");
      out.write("                            <a href=\"all_hotels_list.jsp\">\r\n");
      out.write("                                <img src=\"img/img_cat_home_3.jpg\" alt=\"\" class=\"img-fluid\">\r\n");
      out.write("                                <div class=\"wrapper\">\r\n");
      out.write("                                    <h2>축제3</h2>\r\n");
      out.write("                                    <p>재미있을지도</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-sm-3\">\r\n");
      out.write("                            <a href=\"all_hotels_list.jsp\">\r\n");
      out.write("                                <img src=\"img/img_cat_home_3.jpg\" alt=\"\" class=\"img-fluid\">\r\n");
      out.write("                                <div class=\"wrapper\">\r\n");
      out.write("                                    <h2>축제4</h2>\r\n");
      out.write("                                    <p>재미있을지도</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div> <br><br>\r\n");
      out.write("        <!-- 월별 축제 이미지 끝 -->\r\n");
      out.write("    \r\n");
      out.write("        <!-- 추천 축제 -->\r\n");
      out.write("        <div class=\"main_title\">\r\n");
      out.write("            <h2>추천 축제: <span>꼴뚜기 잡기 대★소★동</span></h2>\r\n");
      out.write("            <p>솔직히 이 축제가 재밌을거라곤 말 못하겠어요.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- 추천 축제 캐러셀 -->\r\n");
      out.write("        <div class=\"owl-carousel owl-theme list_carousel add_bottom_30\">\r\n");
      out.write("                <div class=\"item\">\r\n");
      out.write("                    <div class=\"tour_container\">\r\n");
      out.write("                        <div class=\"ribbon_3 popular\"><span>인기</span></div>\r\n");
      out.write("                        <div class=\"img_container\">\r\n");
      out.write("                            <a href=\"single_tour.jsp\">\r\n");
      out.write("                                <img src=\"img/tour_box_1.jpg\" width=\"800\" height=\"533\" class=\"img-fluid\" alt=\"image\">\r\n");
      out.write("                                <div class=\"short_info\">\r\n");
      out.write("                                    <span class=\"price\">꼴뚜기.jpeg</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"tour_title\">\r\n");
      out.write("                            <h3><strong>꼴뚜기</strong> 투어</h3>\r\n");
      out.write("                            <div class=\"rating\">\r\n");
      out.write("                                <i class=\"icon-smile voted\"></i><i class=\"icon-smile voted\"></i><i class=\"icon-smile voted\"></i><i class=\"icon-smile voted\"></i><i class=\"icon-smile voted\"></i><small>(75)</small>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- end rating -->\r\n");
      out.write("                            <div class=\"wishlist\">\r\n");
      out.write("                                <a class=\"tooltip_flip tooltip-effect-1\" href=\"javascript:void(0);\">+<span class=\"tooltip-content-flip\"><span class=\"tooltip-back\">코스에 추가하기</span></span></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- End 코스에 추가하기-->\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- End box tour -->\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- /item -->\r\n");
      out.write("                <div class=\"item\">\r\n");
      out.write("                    <div class=\"tour_container\">\r\n");
      out.write("                        <div class=\"ribbon_3 popular\"><span>한달 남음</span></div>\r\n");
      out.write("                        <div class=\"img_container\">\r\n");
      out.write("                            <a href=\"single_tour.jsp\">\r\n");
      out.write("                                <img src=\"img/tour_box_2.jpg\" width=\"800\" height=\"533\" class=\"img-fluid\" alt=\"image\">\r\n");
      out.write("                                <div class=\"short_info\">\r\n");
      out.write("                                    <span class=\"price\">망둥어 사냥꾼</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"tour_title\">\r\n");
      out.write("                            <h3><strong>매운탕</strong> 투어</h3>\r\n");
      out.write("                            <div class=\"rating\">\r\n");
      out.write("                                <i class=\"icon-smile voted\"></i><i class=\"icon-smile voted\"></i><i class=\"icon-smile voted\"></i><i class=\"icon-smile voted\"></i><i class=\"icon-smile\"></i><small>(75)</small>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- end rating -->\r\n");
      out.write("                            <div class=\"wishlist\">\r\n");
      out.write("                                <a class=\"tooltip_flip tooltip-effect-1\" href=\"javascript:void(0);\">+<span class=\"tooltip-content-flip\"><span class=\"tooltip-back\">코스에 추가하기</span></span></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- End wish list-->\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- End box tour -->\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- /item -->\r\n");
      out.write("                <div class=\"item\">\r\n");
      out.write("                    <div class=\"tour_container\">\r\n");
      out.write("                        <div class=\"ribbon_3\"><span>평가 좋음</span></div>\r\n");
      out.write("                        <div class=\"img_container\">\r\n");
      out.write("                            <a href=\"single_tour.jsp\">\r\n");
      out.write("                                <img src=\"img/tour_box_2.jpg\" width=\"800\" height=\"533\" class=\"img-fluid\" alt=\"image\">\r\n");
      out.write("                                <div class=\"short_info\">\r\n");
      out.write("                                    <span class=\"price\">망둥어 잡기</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"tour_title\">\r\n");
      out.write("                            <h3><strong>매운탕</strong> 투어</h3>\r\n");
      out.write("                            <div class=\"rating\">\r\n");
      out.write("                                <i class=\"icon-smile voted\"></i><i class=\"icon-smile voted\"></i><i class=\"icon-smile voted\"></i><i class=\"icon-smile voted\"></i><i class=\"icon-smile\"></i><small>(75)</small>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- end rating -->\r\n");
      out.write("                            <div class=\"wishlist\">\r\n");
      out.write("                                <a class=\"tooltip_flip tooltip-effect-1\" href=\"javascript:void(0);\">+<span class=\"tooltip-content-flip\"><span class=\"tooltip-back\">코스에 추가하기</span></span></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- End wish list-->\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- End box tour -->\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- /item -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 추천 축제 캐러셀 끝 -->\r\n");
      out.write("\t\t\r\n");
      out.write("        <p class=\"text-center nopadding\">\r\n");
      out.write("            <a href=\"#\" class=\"btn_1 medium\"><i class=\"icon-eye-7\"></i> 모든 축제 보기 (144) </a>\r\n");
      out.write("        </p> <br><br>\r\n");
      out.write("        \r\n");
      out.write("        <!-- 내 근처의 축제 -->\r\n");
      out.write("        <div class=\"main_title\">\r\n");
      out.write("            <h2>근처 축제: <span> 오랑우탄 조련 축제 </span></h2>\r\n");
      out.write("            <p>근처에 사는데 주변 축제 정도는 놀러 가봐야죠! 정신나갈거같애정신나갈거같애정신나갈거같애정신나갈거같애정신나갈거같애정신나갈거같애정신나갈거같애정신나갈거같애정신나갈거같애정신나갈거같애정신나갈거같애정신나갈거같애정신나갈거같애정신나갈거같애정신나갈거같애</p>\r\n");
      out.write("            <a href=\"#\" class=\"btn_1\">자세히 보기</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- 추천 축제 캐러셀 -->\r\n");
      out.write("        <div class=\"owl-carousel owl-theme list_carousel add_bottom_30\">\r\n");
      out.write("                <div class=\"item\">\r\n");
      out.write("                    <div class=\"tour_container\">\r\n");
      out.write("                        <div class=\"ribbon_3 popular\"><span>인기</span></div>\r\n");
      out.write("                        <div class=\"img_container\">\r\n");
      out.write("                            <a href=\"single_tour.jsp\">\r\n");
      out.write("                                <img src=\"img/tour_box_1.jpg\" width=\"800\" height=\"533\" class=\"img-fluid\" alt=\"image\">\r\n");
      out.write("                                <div class=\"short_info\">\r\n");
      out.write("                                    <span class=\"price\">꼴뚜기.jpeg</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"tour_title\">\r\n");
      out.write("                            <h3><strong>꼴뚜기</strong> 투어</h3>\r\n");
      out.write("                            <div class=\"rating\">\r\n");
      out.write("                                <i class=\"icon-smile voted\"></i><i class=\"icon-smile voted\"></i><i class=\"icon-smile voted\"></i><i class=\"icon-smile voted\"></i><i class=\"icon-smile voted\"></i><small>(75)</small>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- end rating -->\r\n");
      out.write("                            <div class=\"wishlist\">\r\n");
      out.write("                                <a class=\"tooltip_flip tooltip-effect-1\" href=\"javascript:void(0);\">+<span class=\"tooltip-content-flip\"><span class=\"tooltip-back\">코스에 추가하기</span></span></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- End 코스에 추가하기-->\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- End box tour -->\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- /item -->\r\n");
      out.write("                <div class=\"item\">\r\n");
      out.write("                    <div class=\"tour_container\">\r\n");
      out.write("                        <div class=\"ribbon_3 popular\"><span>한달 남음</span></div>\r\n");
      out.write("                        <div class=\"img_container\">\r\n");
      out.write("                            <a href=\"single_tour.jsp\">\r\n");
      out.write("                                <img src=\"img/tour_box_2.jpg\" width=\"800\" height=\"533\" class=\"img-fluid\" alt=\"image\">\r\n");
      out.write("                                <div class=\"short_info\">\r\n");
      out.write("                                    <span class=\"price\">망둥어 사냥꾼</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"tour_title\">\r\n");
      out.write("                            <h3><strong>매운탕</strong> 투어</h3>\r\n");
      out.write("                            <div class=\"rating\">\r\n");
      out.write("                                <i class=\"icon-smile voted\"></i><i class=\"icon-smile voted\"></i><i class=\"icon-smile voted\"></i><i class=\"icon-smile voted\"></i><i class=\"icon-smile\"></i><small>(75)</small>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- end rating -->\r\n");
      out.write("                            <div class=\"wishlist\">\r\n");
      out.write("                                <a class=\"tooltip_flip tooltip-effect-1\" href=\"javascript:void(0);\">+<span class=\"tooltip-content-flip\"><span class=\"tooltip-back\">코스에 추가하기</span></span></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- End wish list-->\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- End box tour -->\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- /item -->\r\n");
      out.write("                <div class=\"item\">\r\n");
      out.write("                    <div class=\"tour_container\">\r\n");
      out.write("                        <div class=\"ribbon_3\"><span>평가 좋음</span></div>\r\n");
      out.write("                        <div class=\"img_container\">\r\n");
      out.write("                            <a href=\"single_tour.jsp\">\r\n");
      out.write("                                <img src=\"img/tour_box_2.jpg\" width=\"800\" height=\"533\" class=\"img-fluid\" alt=\"image\">\r\n");
      out.write("                                <div class=\"short_info\">\r\n");
      out.write("                                    <span class=\"price\">망둥어 잡기</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"tour_title\">\r\n");
      out.write("                            <h3><strong>매운탕</strong> 투어</h3>\r\n");
      out.write("                            <div class=\"rating\">\r\n");
      out.write("                                <i class=\"icon-smile voted\"></i><i class=\"icon-smile voted\"></i><i class=\"icon-smile voted\"></i><i class=\"icon-smile voted\"></i><i class=\"icon-smile\"></i><small>(75)</small>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- end rating -->\r\n");
      out.write("                            <div class=\"wishlist\">\r\n");
      out.write("                                <a class=\"tooltip_flip tooltip-effect-1\" href=\"javascript:void(0);\">+<span class=\"tooltip-content-flip\"><span class=\"tooltip-back\">코스에 추가하기</span></span></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- End wish list-->\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- End box tour -->\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- /item -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 추천 축제 캐러셀 끝 -->\r\n");
      out.write("        \r\n");
      out.write("    </div><!-- End container -->\r\n");
      out.write("\r\n");
      out.write("    </main>\r\n");
      out.write("\t<!-- End main -->\r\n");
      out.write("\t\r\n");
      out.write("\t<footer class=\"revealed\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                    <h3>도움이 필요하세요?</h3>\r\n");
      out.write("                    <a href=\"tel://004542344599\" id=\"phone\">+82 10 3333 4444</a>\r\n");
      out.write("                    <a href=\"mailto:help@citytours.com\" id=\"email_footer\">help@festi.bbang</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                    <h3>축축빵빵</h3>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"#\">축축빵빵은요!</a></li>\r\n");
      out.write("                        <li><a href=\"#\">FAQ</a></li>\r\n");
      out.write("                        <li><a href=\"#\">로그인</a></li>\r\n");
      out.write("                        <li><a href=\"member/memberJoin.do\">회원가입</a></li>\r\n");
      out.write("                         <li><a href=\"#\">이용 약관</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                    <h3>언어 선택</h3>\r\n");
      out.write("                    <div class=\"styled-select\">\r\n");
      out.write("                        <select name=\"lang\" id=\"lang\">\r\n");
      out.write("                            <option value=\"Korean\" selected>한국어</option>\r\n");
      out.write("                            <option value=\"English\">English</option>\r\n");
      out.write("                            <option value=\"Japanese\">日本語</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div><!-- End row -->\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-12\">\r\n");
      out.write("                    <div id=\"social_footer\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"icon-facebook\"></i></a></li>\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"icon-twitter\"></i></a></li>\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"icon-google\"></i></a></li>\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"icon-instagram\"></i></a></li>\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"icon-pinterest\"></i></a></li>\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"icon-vimeo\"></i></a></li>\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"icon-youtube-play\"></i></a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <p>© Kosmo73 - Blue 2021</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div><!-- End row -->\r\n");
      out.write("        </div><!-- End container -->\r\n");
      out.write("    </footer><!-- End footer -->\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"toTop\"></div><!-- Back to top button -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Search Menu -->\r\n");
      out.write("\t<div class=\"search-overlay-menu\">\r\n");
      out.write("\t\t<span class=\"search-overlay-close\"><i class=\"icon_set_1_icon-77\"></i></span>\r\n");
      out.write("\t\t<form role=\"search\" id=\"searchform\" method=\"get\">\r\n");
      out.write("\t\t\t<input value=\"\" name=\"q\" type=\"search\" placeholder=\"Search...\" />\r\n");
      out.write("\t\t\t<button type=\"submit\"><i class=\"icon_set_1_icon-78\"></i>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div><!-- End Search Menu -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Sign In Popup -->\r\n");
      out.write("\t<div id=\"sign-in-dialog\" class=\"zoom-anim-dialog mfp-hide\">\r\n");
      out.write("\t\t<div class=\"small-dialog-header\">\r\n");
      out.write("\t\t\t<h3>로그인</h3>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<form>\r\n");
      out.write("\t\t\t<div class=\"sign-in-wrapper\">\r\n");
      out.write("                <div class=\"snsLogin\" style=\"text-align: center;\">\r\n");
      out.write("                    <input type=\"button\" style=\"width: 270px; height: 48px; background-color: #FFFFFF; background: url(img/login/naver_login.PNG); border: 0; outline: 0;\" >\r\n");
      out.write("                    <input type=\"button\" style=\"width: 270px; height: 48px; background-color: #FFFFFF; background: url(img/login/kakao_login.png); border: 0; outline: 0;\" >\r\n");
      out.write("                </div>\r\n");
      out.write("\t\t\t\t<div class=\"divider\"><span>Or</span></div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label>Email</label>\r\n");
      out.write("\t\t\t\t\t<input type=\"email\" class=\"form-control\" name=\"email\" id=\"email\">\r\n");
      out.write("\t\t\t\t\t<i class=\"icon_mail_alt\"></i>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label>Password</label>\r\n");
      out.write("\t\t\t\t\t<input type=\"password\" class=\"form-control\" name=\"password\" id=\"password\" value=\"\">\r\n");
      out.write("\t\t\t\t\t<i class=\"icon_lock_alt\"></i>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix add_bottom_15\">\r\n");
      out.write("\t\t\t\t\t<div class=\"checkboxes float-left\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"remember-me\" type=\"checkbox\" name=\"check\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"remember-me\">기억하기</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"float-right\"><a id=\"forgot\" href=\"javascript:void(0);\">비밀번호를 잊어버리셨나요?</a></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"text-center\"><input type=\"submit\" value=\"로그인\" class=\"btn_login\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"text-center\">\r\n");
      out.write("\t\t\t\t\t계정이 없으신가요? <a href=\"member/memberJoin.do\">회원가입</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"forgot_pw\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<!-- <label>Please confirm login email below</label> -->\r\n");
      out.write("                        <label>하단에 로그인 이메일을 작성해주세요.</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"email\" class=\"form-control\" name=\"email_forgot\" id=\"email_forgot\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"icon_mail_alt\"></i>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- <p>You will receive an email containing a link allowing you to reset your password to a new preferred one.</p> -->\r\n");
      out.write("                    <p>새 비밀번호로 재설정 할 수 있는 링크가 포함된 이메일을 받게됩니다.</p>\r\n");
      out.write("\t\t\t\t\t<div class=\"text-center\"><input type=\"submit\" value=\"비밀번호 재설정\" class=\"btn_1\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<!--form -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /Sign In Popup -->\r\n");
      out.write("\r\n");
      out.write(" \t<!-- Common scripts -->\r\n");
      out.write("\t<script src=\"js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/common_scripts_min.js\"></script>\r\n");
      out.write("\t<script src=\"js/functions.js\"></script>\r\n");
      out.write("\r\n");
      out.write(" \t<!-- Specific scripts -->\r\n");
      out.write("\t<script src=\"js/morphext.min.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t$(\"#js-rotating\").Morphext({\r\n");
      out.write("\t\tanimation: \"fadeIn\", // Overrides default \"bounceIn\"\r\n");
      out.write("\t\tseparator: \",\", // Overrides default \",\"\r\n");
      out.write("\t\tspeed: 2000, // Overrides default 2000\r\n");
      out.write("\t\tcomplete: function () {\r\n");
      out.write("\t\t\t// Overrides default empty function\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
